### ISSUE TITLE
Can't leave correctly from voice channel

### ISSUE THREAD

**Issue by xyaman** [skwair/harmony#53]
**Description**
Joining to a voice channel always works well, but leaving does not always work correctly. Sometimes works fine, but not always.

**What did you do?**
I just try to connect and then disconnect from a specific voice channel.
Here is the message handler
```go
if m.Content == "!connect" {
	mu.Lock()
	defer mu.Unlock()

	_, err := b.client.JoinVoiceChannel(context.TODO(), m.GuildID, channelID, false, false)
	if err != nil {
		fmt.Println("Error", err)
		return
	}
} else if m.Content == "!disconnect" {
	mu.Lock()
	defer mu.Unlock()
	b.client.LeaveVoiceChannel(context.TODO(), m.GuildID)
}
```

**What did you expect to see?**
I expected to always disconnect correctly.

**What did you see instead?**
I'm using the default logger. This is the output:
```
[DEBUG] disconnecting from the voice server
[DEBUG] stopped Opus sender
[DEBUG] stopped UDP heartbeater
[DEBUG] stopped voice connection heartbeater
[DEBUG] stopped Opus receiver
[DEBUG] stopped voice connection event listener
[DEBUG] stopped voice connection manager
[DEBUG] sent payload: {code: 1, data: 8}
[DEBUG] received payload: {code: 11}
[DEBUG] sent payload: {code: 1, data: 8}
[DEBUG] received payload: {code: 11}
[DEBUG] sent payload: {code: 1, data: 8}
[DEBUG] received payload: {code: 11}
[DEBUG] sent payload: {code: 1, data: 8}
[DEBUG] received payload: {code: 11}
[DEBUG] sent payload: {code: 1, data: 8}
[DEBUG] received payload: {code: 11}
```
and never disconnects

**What version of the module are you using ?**
I'm using `v0.14.0`

**Comment by skwair** [comment]
This issue seems to happen when the bot detects some audio while connected to the voice channel. If no one is connected with the bot or if everyone is muted/does not make any sound, it works fine.

Will investigate to see from where exactly the issue comes from. Thanks for reporting it!

**Comment by skwair** [comment]
It looks like the issue comes from this line: https://github.com/skwair/harmony/blob/6abd247fc5668b0ad04de7a17ad5ff0e55b6bfba/voice/opus.go#L116
If some audio data is received by the bot while connected to a voice channel, it will try to send it through this channel; but if no one is listening on the other side, it'll block forever.

Changing it to something like:

```go
select {
case ch <- &rtpFrame{raw: buf, size: l}:
default:
}
```
should fix the issue, discarding the audio data if no one is listening for it.
