### ISSUE TITLE
Client fails to properly disconnect when Gateway sends reconnect payload

### ISSUE THREAD

**Issue by skwair** [skwair/harmony#79]
**Description**

When receiving an opcode 7 reconnect payload from the Gateway, Harmony fails to disconnect, and thus to reconnect after.

Initially reported by 0x5444 on Discord, thanks!

**What did you do?**

Let a bot run until it receives the before-mentioned payload.

**What did you expect to see?**

The bot should reconnect successfully.

**What did you see instead?**

With debug enabled, these are the last logs printed:

```
...
2020/12/01 17:55:01 [DEBUG] sent payload: {code: 1, data: 9}
2020/12/01 17:55:01 [DEBUG] received payload: {code: 11}
2020/12/01 17:55:21 [DEBUG] received payload: {code: 7}
2020/12/01 17:55:21 [DEBUG] stopped gateway heartbeater
2020/12/01 17:55:21 [DEBUG] disconnecting from the gateway
2020/12/01 17:55:21 [DEBUG] stopped gateway connection manager
```

The payload listener does not seem to stop properly so it's very likely that this bug comes from this function:
https://github.com/skwair/harmony/blob/40b27cf8c1ac3d3c113346b9d5af6cf865605a95/internal/payload/listen.go#L19-L43

**What version of the module are you using ?**

`v0.17.0`

**Comment by codemicro** [comment]
0x5444 be me :P

**Comment by skwair** [comment]
And I forgot to link the PR to the issue, but hopefully #80 fixed this :slightly_smiling_face:
